import '../globals.css'

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default async function RootLayout({ children }) {

  const supabase = createServerComponentClient({ cookies })
  const {data : { session }} = await supabase.auth.getSession()

  if(session){
    redirect("/")
  }

 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
